### ISSUE TITLE
it's not work with jquery 3.1.0

### ISSUE THREAD

**Issue by liron-li** [sconsult/croppic#254]
`Uncaught TypeError: url.indexOf is not a function`

I think it is caused by  https://github.com/sconsult/croppic/blob/master/croppic.js#L313

**Comment by xtwoend** [comment]
change img.load(fn)  to img.on('load', fn)

**Comment by liron-li** [comment]
thanks
