### PR TITLE
Update croppic.js

### PR DESCRIPTION
**Pull request by onslaughtilus**
First of all, thanks for your croppic plugin, it is awesome!!! 

However while I was trying to make it work with jquery 2.1.1+jquery-migrate-1.2.1 and I've detected one problem in the Eye Candy sample (the other samples works like a charm ;)) 
In the Eye Candy sample, after the image is selected, when you push the crop button, the Firefox browser raises the following javascript error (located at line 450 of croppic.js): 

TypeError: o.imgEyecandy.hide is not a function

To solve it I've just added the following line at line 406 position:

that.imgEyecandy = that.img.clone(); 

Please review the pull request and if you consider it right merge it with your code.

Cheers,

Eduardo Crespo

### CODE REVIEW

**Comment by sconsult** [comment]
Code will be upgraded to support latest 2.1.3 which FF version did you run it in ?

**Comment by sconsult** [comment]
this has been implemented in the latest version
